import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import "@/app/_styles/scss/main.scss";
import "./globals.css";
// import ScrollToTop from "@/components/common/ScrollTop";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "aos/dist/aos.css";
import "rc-slider/assets/index.css";

import ClientProviders from "@/components/ClientProviders";

import DefaultHeader from "@/components/common/header/DefaultHeader";
import MobileMenu from "@/components/common/mobile-menu/MobileMenu";
import Footer from "@/components/common/footer";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--body-font-family",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--title-font-family",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${dmSans.variable}`}>
        <ClientProviders>
          <div className="wrapper">
            {/* Main Header Nav */}
            <DefaultHeader />
            {/* End Main Header Nav */}

            {/* Mobile Nav  */}
            <MobileMenu />
            {/* End Mobile Nav  */}

            {children}

            {/* Start Our Footer */}
            <section className="footer-style1 pt60 pb-0">
              <Footer />
            </section>
            {/* End Our Footer */}
          </div>
          {/* <ScrollToTop /> */}
        </ClientProviders>
      </body>
    </html>
  );
}
